// Code generated by MockGen. DO NOT EDIT.
// Source: node_handler.go
//
// Generated by this command:
//
//	mockgen -source=node_handler.go -destination=mocks/node_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/6ermvH/log-parser/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MocknodeQuery is a mock of nodeQuery interface.
type MocknodeQuery struct {
	ctrl     *gomock.Controller
	recorder *MocknodeQueryMockRecorder
	isgomock struct{}
}

// MocknodeQueryMockRecorder is the mock recorder for MocknodeQuery.
type MocknodeQueryMockRecorder struct {
	mock *MocknodeQuery
}

// NewMocknodeQuery creates a new mock instance.
func NewMocknodeQuery(ctrl *gomock.Controller) *MocknodeQuery {
	mock := &MocknodeQuery{ctrl: ctrl}
	mock.recorder = &MocknodeQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknodeQuery) EXPECT() *MocknodeQueryMockRecorder {
	return m.recorder
}

// GetNodeDetails mocks base method.
func (m *MocknodeQuery) GetNodeDetails(ctx context.Context, id int64) (service.NodeDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeDetails", ctx, id)
	ret0, _ := ret[0].(service.NodeDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeDetails indicates an expected call of GetNodeDetails.
func (mr *MocknodeQueryMockRecorder) GetNodeDetails(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeDetails", reflect.TypeOf((*MocknodeQuery)(nil).GetNodeDetails), ctx, id)
}
