// Code generated by MockGen. DO NOT EDIT.
// Source: parse_handler.go
//
// Generated by this command:
//
//	mockgen -source=parse_handler.go -destination=mocks/parse_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/6ermvH/log-parser/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockparseRunner is a mock of parseRunner interface.
type MockparseRunner struct {
	ctrl     *gomock.Controller
	recorder *MockparseRunnerMockRecorder
	isgomock struct{}
}

// MockparseRunnerMockRecorder is the mock recorder for MockparseRunner.
type MockparseRunnerMockRecorder struct {
	mock *MockparseRunner
}

// NewMockparseRunner creates a new mock instance.
func NewMockparseRunner(ctrl *gomock.Controller) *MockparseRunner {
	mock := &MockparseRunner{ctrl: ctrl}
	mock.recorder = &MockparseRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockparseRunner) EXPECT() *MockparseRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockparseRunner) Run(ctx context.Context, path string) (service.ParseResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, path)
	ret0, _ := ret[0].(service.ParseResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockparseRunnerMockRecorder) Run(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockparseRunner)(nil).Run), ctx, path)
}
