// Code generated by MockGen. DO NOT EDIT.
// Source: parse.go
//
// Generated by this command:
//
//	mockgen -source=parse.go -destination=mocks/parse_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/6ermvH/log-parser/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockparseRepo is a mock of parseRepo interface.
type MockparseRepo struct {
	ctrl     *gomock.Controller
	recorder *MockparseRepoMockRecorder
	isgomock struct{}
}

// MockparseRepoMockRecorder is the mock recorder for MockparseRepo.
type MockparseRepoMockRecorder struct {
	mock *MockparseRepo
}

// NewMockparseRepo creates a new mock instance.
func NewMockparseRepo(ctrl *gomock.Controller) *MockparseRepo {
	mock := &MockparseRepo{ctrl: ctrl}
	mock.recorder = &MockparseRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockparseRepo) EXPECT() *MockparseRepoMockRecorder {
	return m.recorder
}

// InsertProcessingLog mocks base method.
func (m *MockparseRepo) InsertProcessingLog(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertProcessingLog", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertProcessingLog indicates an expected call of InsertProcessingLog.
func (mr *MockparseRepoMockRecorder) InsertProcessingLog(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertProcessingLog", reflect.TypeOf((*MockparseRepo)(nil).InsertProcessingLog), ctx, id)
}

// MarkLogFailed mocks base method.
func (m *MockparseRepo) MarkLogFailed(ctx context.Context, id uuid.UUID, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkLogFailed", ctx, id, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkLogFailed indicates an expected call of MarkLogFailed.
func (mr *MockparseRepoMockRecorder) MarkLogFailed(ctx, id, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkLogFailed", reflect.TypeOf((*MockparseRepo)(nil).MarkLogFailed), ctx, id, message)
}

// SaveDomainLog mocks base method.
func (m *MockparseRepo) SaveDomainLog(ctx context.Context, id uuid.UUID, dlog domain.Log) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDomainLog", ctx, id, dlog)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDomainLog indicates an expected call of SaveDomainLog.
func (mr *MockparseRepoMockRecorder) SaveDomainLog(ctx, id, dlog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDomainLog", reflect.TypeOf((*MockparseRepo)(nil).SaveDomainLog), ctx, id, dlog)
}

// MocklogParser is a mock of logParser interface.
type MocklogParser struct {
	ctrl     *gomock.Controller
	recorder *MocklogParserMockRecorder
	isgomock struct{}
}

// MocklogParserMockRecorder is the mock recorder for MocklogParser.
type MocklogParserMockRecorder struct {
	mock *MocklogParser
}

// NewMocklogParser creates a new mock instance.
func NewMocklogParser(ctrl *gomock.Controller) *MocklogParser {
	mock := &MocklogParser{ctrl: ctrl}
	mock.recorder = &MocklogParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklogParser) EXPECT() *MocklogParserMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MocklogParser) Parse(path string) (domain.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", path)
	ret0, _ := ret[0].(domain.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MocklogParserMockRecorder) Parse(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MocklogParser)(nil).Parse), path)
}

// Preflight mocks base method.
func (m *MocklogParser) Preflight(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preflight", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Preflight indicates an expected call of Preflight.
func (mr *MocklogParserMockRecorder) Preflight(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preflight", reflect.TypeOf((*MocklogParser)(nil).Preflight), path)
}
