// Code generated by MockGen. DO NOT EDIT.
// Source: query.go
//
// Generated by this command:
//
//	mockgen -source=query.go -destination=mocks/query_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	postgres "github.com/6ermvH/log-parser/internal/storage/postgres"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockqueryRepo is a mock of queryRepo interface.
type MockqueryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockqueryRepoMockRecorder
	isgomock struct{}
}

// MockqueryRepoMockRecorder is the mock recorder for MockqueryRepo.
type MockqueryRepoMockRecorder struct {
	mock *MockqueryRepo
}

// NewMockqueryRepo creates a new mock instance.
func NewMockqueryRepo(ctrl *gomock.Controller) *MockqueryRepo {
	mock := &MockqueryRepo{ctrl: ctrl}
	mock.recorder = &MockqueryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockqueryRepo) EXPECT() *MockqueryRepoMockRecorder {
	return m.recorder
}

// CountByLog mocks base method.
func (m *MockqueryRepo) CountByLog(ctx context.Context, logID uuid.UUID) (postgres.Counts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByLog", ctx, logID)
	ret0, _ := ret[0].(postgres.Counts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByLog indicates an expected call of CountByLog.
func (mr *MockqueryRepoMockRecorder) CountByLog(ctx, logID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByLog", reflect.TypeOf((*MockqueryRepo)(nil).CountByLog), ctx, logID)
}

// GetLog mocks base method.
func (m *MockqueryRepo) GetLog(ctx context.Context, id uuid.UUID) (postgres.LogMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLog", ctx, id)
	ret0, _ := ret[0].(postgres.LogMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLog indicates an expected call of GetLog.
func (mr *MockqueryRepoMockRecorder) GetLog(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLog", reflect.TypeOf((*MockqueryRepo)(nil).GetLog), ctx, id)
}

// GetNode mocks base method.
func (m *MockqueryRepo) GetNode(ctx context.Context, id int64) (postgres.NodeRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNode", ctx, id)
	ret0, _ := ret[0].(postgres.NodeRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNode indicates an expected call of GetNode.
func (mr *MockqueryRepoMockRecorder) GetNode(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNode", reflect.TypeOf((*MockqueryRepo)(nil).GetNode), ctx, id)
}

// GetNodeInfo mocks base method.
func (m *MockqueryRepo) GetNodeInfo(ctx context.Context, nodeID int64) (postgres.NodeInfoRow, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeInfo", ctx, nodeID)
	ret0, _ := ret[0].(postgres.NodeInfoRow)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetNodeInfo indicates an expected call of GetNodeInfo.
func (mr *MockqueryRepoMockRecorder) GetNodeInfo(ctx, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeInfo", reflect.TypeOf((*MockqueryRepo)(nil).GetNodeInfo), ctx, nodeID)
}

// ListNodes mocks base method.
func (m *MockqueryRepo) ListNodes(ctx context.Context, logID uuid.UUID) ([]postgres.NodeRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNodes", ctx, logID)
	ret0, _ := ret[0].([]postgres.NodeRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNodes indicates an expected call of ListNodes.
func (mr *MockqueryRepoMockRecorder) ListNodes(ctx, logID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNodes", reflect.TypeOf((*MockqueryRepo)(nil).ListNodes), ctx, logID)
}

// ListPortsByLog mocks base method.
func (m *MockqueryRepo) ListPortsByLog(ctx context.Context, logID uuid.UUID) ([]postgres.PortRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPortsByLog", ctx, logID)
	ret0, _ := ret[0].([]postgres.PortRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPortsByLog indicates an expected call of ListPortsByLog.
func (mr *MockqueryRepoMockRecorder) ListPortsByLog(ctx, logID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPortsByLog", reflect.TypeOf((*MockqueryRepo)(nil).ListPortsByLog), ctx, logID)
}

// ListPortsByNode mocks base method.
func (m *MockqueryRepo) ListPortsByNode(ctx context.Context, nodeID int64) ([]postgres.PortRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPortsByNode", ctx, nodeID)
	ret0, _ := ret[0].([]postgres.PortRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPortsByNode indicates an expected call of ListPortsByNode.
func (mr *MockqueryRepoMockRecorder) ListPortsByNode(ctx, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPortsByNode", reflect.TypeOf((*MockqueryRepo)(nil).ListPortsByNode), ctx, nodeID)
}

// NodeExists mocks base method.
func (m *MockqueryRepo) NodeExists(ctx context.Context, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NodeExists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NodeExists indicates an expected call of NodeExists.
func (mr *MockqueryRepoMockRecorder) NodeExists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeExists", reflect.TypeOf((*MockqueryRepo)(nil).NodeExists), ctx, id)
}
