// Code generated by MockGen. DO NOT EDIT.
// Source: health_handler.go
//
// Generated by this command:
//
//	mockgen -source=health_handler.go -destination=mocks/health_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockhealthChecker is a mock of healthChecker interface.
type MockhealthChecker struct {
	ctrl     *gomock.Controller
	recorder *MockhealthCheckerMockRecorder
	isgomock struct{}
}

// MockhealthCheckerMockRecorder is the mock recorder for MockhealthChecker.
type MockhealthCheckerMockRecorder struct {
	mock *MockhealthChecker
}

// NewMockhealthChecker creates a new mock instance.
func NewMockhealthChecker(ctrl *gomock.Controller) *MockhealthChecker {
	mock := &MockhealthChecker{ctrl: ctrl}
	mock.recorder = &MockhealthCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhealthChecker) EXPECT() *MockhealthCheckerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockhealthChecker) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockhealthCheckerMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockhealthChecker)(nil).Ping), ctx)
}
