// Code generated by MockGen. DO NOT EDIT.
// Source: log_handler.go
//
// Generated by this command:
//
//	mockgen -source=log_handler.go -destination=mocks/log_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/6ermvH/log-parser/internal/service"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MocklogMetaQuery is a mock of logMetaQuery interface.
type MocklogMetaQuery struct {
	ctrl     *gomock.Controller
	recorder *MocklogMetaQueryMockRecorder
	isgomock struct{}
}

// MocklogMetaQueryMockRecorder is the mock recorder for MocklogMetaQuery.
type MocklogMetaQueryMockRecorder struct {
	mock *MocklogMetaQuery
}

// NewMocklogMetaQuery creates a new mock instance.
func NewMocklogMetaQuery(ctrl *gomock.Controller) *MocklogMetaQuery {
	mock := &MocklogMetaQuery{ctrl: ctrl}
	mock.recorder = &MocklogMetaQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklogMetaQuery) EXPECT() *MocklogMetaQueryMockRecorder {
	return m.recorder
}

// GetLogMeta mocks base method.
func (m *MocklogMetaQuery) GetLogMeta(ctx context.Context, id uuid.UUID) (service.LogMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogMeta", ctx, id)
	ret0, _ := ret[0].(service.LogMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogMeta indicates an expected call of GetLogMeta.
func (mr *MocklogMetaQueryMockRecorder) GetLogMeta(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogMeta", reflect.TypeOf((*MocklogMetaQuery)(nil).GetLogMeta), ctx, id)
}
