// Code generated by MockGen. DO NOT EDIT.
// Source: parse_handler.go
//
// Generated by this command:
//
//	mockgen -source=parse_handler.go -destination=mocks/parse_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockparseSubmitter is a mock of parseSubmitter interface.
type MockparseSubmitter struct {
	ctrl     *gomock.Controller
	recorder *MockparseSubmitterMockRecorder
	isgomock struct{}
}

// MockparseSubmitterMockRecorder is the mock recorder for MockparseSubmitter.
type MockparseSubmitterMockRecorder struct {
	mock *MockparseSubmitter
}

// NewMockparseSubmitter creates a new mock instance.
func NewMockparseSubmitter(ctrl *gomock.Controller) *MockparseSubmitter {
	mock := &MockparseSubmitter{ctrl: ctrl}
	mock.recorder = &MockparseSubmitterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockparseSubmitter) EXPECT() *MockparseSubmitterMockRecorder {
	return m.recorder
}

// Submit mocks base method.
func (m *MockparseSubmitter) Submit(ctx context.Context, path string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, path)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockparseSubmitterMockRecorder) Submit(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockparseSubmitter)(nil).Submit), ctx, path)
}
