// Code generated by MockGen. DO NOT EDIT.
// Source: ports_handler.go
//
// Generated by this command:
//
//	mockgen -source=ports_handler.go -destination=mocks/ports_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/6ermvH/log-parser/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockportsQuery is a mock of portsQuery interface.
type MockportsQuery struct {
	ctrl     *gomock.Controller
	recorder *MockportsQueryMockRecorder
	isgomock struct{}
}

// MockportsQueryMockRecorder is the mock recorder for MockportsQuery.
type MockportsQueryMockRecorder struct {
	mock *MockportsQuery
}

// NewMockportsQuery creates a new mock instance.
func NewMockportsQuery(ctrl *gomock.Controller) *MockportsQuery {
	mock := &MockportsQuery{ctrl: ctrl}
	mock.recorder = &MockportsQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockportsQuery) EXPECT() *MockportsQueryMockRecorder {
	return m.recorder
}

// ListPortsForNode mocks base method.
func (m *MockportsQuery) ListPortsForNode(ctx context.Context, nodeID int64) ([]service.Port, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPortsForNode", ctx, nodeID)
	ret0, _ := ret[0].([]service.Port)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPortsForNode indicates an expected call of ListPortsForNode.
func (mr *MockportsQueryMockRecorder) ListPortsForNode(ctx, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPortsForNode", reflect.TypeOf((*MockportsQuery)(nil).ListPortsForNode), ctx, nodeID)
}
