// Code generated by MockGen. DO NOT EDIT.
// Source: topology_handler.go
//
// Generated by this command:
//
//	mockgen -source=topology_handler.go -destination=mocks/topology_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/6ermvH/log-parser/internal/service"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MocktopologyQuery is a mock of topologyQuery interface.
type MocktopologyQuery struct {
	ctrl     *gomock.Controller
	recorder *MocktopologyQueryMockRecorder
	isgomock struct{}
}

// MocktopologyQueryMockRecorder is the mock recorder for MocktopologyQuery.
type MocktopologyQueryMockRecorder struct {
	mock *MocktopologyQuery
}

// NewMocktopologyQuery creates a new mock instance.
func NewMocktopologyQuery(ctrl *gomock.Controller) *MocktopologyQuery {
	mock := &MocktopologyQuery{ctrl: ctrl}
	mock.recorder = &MocktopologyQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktopologyQuery) EXPECT() *MocktopologyQueryMockRecorder {
	return m.recorder
}

// GetTopology mocks base method.
func (m *MocktopologyQuery) GetTopology(ctx context.Context, logID uuid.UUID) (service.Topology, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopology", ctx, logID)
	ret0, _ := ret[0].(service.Topology)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopology indicates an expected call of GetTopology.
func (mr *MocktopologyQueryMockRecorder) GetTopology(ctx, logID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopology", reflect.TypeOf((*MocktopologyQuery)(nil).GetTopology), ctx, logID)
}
